{% set name = "perl-module-scandeps" %}
{% set version = "1.34" %}
{% set sha256 = "cac530e5cfc413e067797c7d237c6c5cd32915c3d9faee5d94035c8f3a8550eb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/R/RS/RSCHUPP/Module-ScanDeps-1.34.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-getopt-long
    - perl-extutils-makemaker
    - perl-text-parsewords
    - perl-test-requires
    - perl-module-metadata
    - perl-version
    - perl-file-temp

  run:
    - perl
    - perl-text-parsewords
    - perl-getopt-long
    - perl-version
    - perl-module-metadata
    - perl-file-temp

test:
  imports:
    - Module::ScanDeps

about:
  home: http://metacpan.org/pod/Module::ScanDeps
  license: perl_5
  summary: 'Recursively scan Perl code for dependencies'
