{% set version = "23.09" %}

package:
  name: smashpp
  version: {{ version }}

build:
  # Passes some invalid flags for clang
  skip: True  # [osx]
  number: 2

source:
  url: https://github.com/smortezah/smashpp/archive/refs/tags/{{ version }}.tar.gz
  sha256: 6cda463f339926ba4900a03c90a82aeffd565d28e0f5d59a92c4f252073648bc

requirements:
  build:
    - make
    - cmake
    - {{ compiler('cxx') }}

test:
  commands:
    - smashpp --version 2>&1 | grep {{ version }}

about:
  home: https://github.com/smortezah/smashpp
  license: GPL3
  license_file: LICENSE
  license_family: GPL
  summary: A fast tool to find and visualize rearrangements in DNA sequences
