{% set name = "rnaQUAST" %}
{% set version = "2.2.4" %}
{% set sha256 = "5529fa816e2691a213b1e89f5aad560b99211872992a8624709e93ad805df713" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/ablab/rnaquast/releases/download/v.{{ version}}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]

requirements:
  run:
    - python
    - blast
    - blat
    - busco >=5
    - emboss
    - gmap <2021.02.22, >=2020.03.12
    - gffutils
    - joblib
    - matplotlib-base
    - ucsc-pslsort
    - star
    - samtools

test:
  commands:
    - rnaQUAST.py --test
    - makeblastdb -help
    # test fa_coords from gmap
    - ": | fa_coords | grep 'Error: No contigs were read in.'"

about:
  summary: rnaQUAST is a tool for evaluating RNA-Seq assemblies using reference genome and gene database. In addition, rnaQUAST is also capable of estimating gene database coverage by raw reads and de novo quality assessment using third-party software.
  home: http://cab.spbu.ru/software/rnaquast/
  license: GPLv2

extra:
  skip-lints:
    - should_be_noarch_generic
