{% set name = "perl-image-exiftool" %}
{% set version = "12.70" %}
{% set sha256 = "4cb2522445cc3e3f3bd13904c6aeaeada5fc5a5e2498d7abad2957dcb42caffe" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-12.70.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  
requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
  run:
    - perl

test:
  imports:
    - Image::ExifTool
  commands:
    - exiftool -ver

about:
  home: https://metacpan.org/pod/Image::ExifTool
  license: perl_5
  summary: 'ExifTool is a platform-independent Perl library plus a command-line application for reading, writing and editing meta information in a wide variety of files.'
