{% set version = "0.2.0" %}
{% set git_commit = "2d40525336a6bde547cca7b17b27d56b7b49ff69" %}
{% set sha256 = "763daa24232dd5bf6e8ce5620b1221cd5c66428d2d00d624b33e795ccec225a4" %}

package:
  name: piscem
  version: {{ version }}

build:
  number: 0
  # skip: True  # [osx]

source:
  git_url: https://github.com/COMBINE-lab/piscem
  git_rev: "{{ git_commit }}"
  sha256: {{ sha256 }}

requirements:
  build:
    - rust >=1.60  
    - cmake
    - autoconf
    - make
    - zlib
    - bzip2
    - jemalloc >=5.1.0
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - zlib
    - bzip2
    - jemalloc >=5.1.0
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }} #[osx and x86_64]

test:
  commands:
    - piscem --help

about:
  home: https://github.com/COMBINE-lab/piscem
  license: BSD 3-Clause
  license_file: LICENSE
  summary: piscem is a next-generation compacted colored de Bruijn Graph-based indexer and mapper

extra:
  skip-lints:
    - uses_vcs_url
