{% set version = "0.2.0" %}
{% set git_commit = "ca224984c5f63e123a61529d6b011574107aa910" %}
{% set sha256 = "a0ef2100abb69fe421a181657cabde70b5a715b6d66efbb1b1fea2c460219887" %}

package:
  name: piscem
  version: {{ version }}

build:
  number: 0
  # just for testing OSX more quickly
  skip: True  # [linux]

source:
  git_url: https://github.com/COMBINE-lab/piscem
  git_rev: "{{ git_commit }}"
  sha256: {{ sha256 }}

requirements:
  build:
    - rust >=1.60  
    - cmake
    - autoconf
    - make
    - zlib
    - bzip2
    - jemalloc >=5.1.0
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - zlib
    - bzip2
    - jemalloc >=5.1.0
    - libcxx #[osx]
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }} #[osx and x86_64]

test:
  commands:
    - piscem --help

about:
  home: https://github.com/COMBINE-lab/piscem
  license: BSD 3-Clause
  license_file: LICENSE
  summary: piscem is a next-generation compacted colored de Bruijn Graph-based indexer and mapper

extra:
  skip-lints:
    - uses_vcs_url
