{% set version = "0.2.0" %}
{% set git_commit = "e727ecdeb680c5ef7b25b407bfe689b18cc10c7f" %}
{% set sha256 = "e8c590d756f1ffc8ede13b2904d308ee852504744b16ba0027f097929caecab" %}

package:
  name: piscem
  version: {{ version }}

build:
  number: 0
  # skip: True  # [osx]

source:
  git_url: https://github.com/COMBINE-lab/piscem
  git_rev: "{{ git_commit }}"
  sha256: {{ sha256 }}

requirements:
  build:
    - rust >=1.60  
    - cmake
    - autoconf
    - make
    - zlib
    - bzip2
    - jemalloc >=5.1.0
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - zlib
    - bzip2
    - jemalloc >=5.1.0
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }} #[osx and x86_64]

test:
  commands:
    - piscem --help

about:
  home: https://github.com/COMBINE-lab/piscem
  license: BSD 3-Clause
  license_file: LICENSE
  summary: piscem is a next-generation compacted colored de Bruijn Graph-based indexer and mapper

extra:
  skip-lints:
    - uses_vcs_url
