{% set version = "0.2.0" %}
{% set git_commit = "ffa52d704a2becd0d3985033190cbcfca182b87" %}
{% set sha256 = "3f734075caee59a6b34b46759a5c98c5e96e66177bc6ce474b0658fbf6b29c02" %}

package:
  name: piscem
  version: {{ version }}

build:
  number: 0
  # just for testing OSX more quickly
  skip: True  # [linux]

source:
  git_url: https://github.com/COMBINE-lab/piscem
  git_rev: "{{ git_commit }}"
  sha256: {{ sha256 }}

requirements:
  build:
    - rust >=1.60  
    - cmake
    - autoconf
    - make
    - zlib
    - bzip2
    - jemalloc >=5.1.0
    - {{ compiler('cxx') }}
    - pkg-config
  host:
    - zlib
    - bzip2
    - jemalloc >=5.1.0
  run:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }} #[osx and x86_64]

test:
  commands:
    - piscem --help

about:
  home: https://github.com/COMBINE-lab/piscem
  license: BSD 3-Clause
  license_file: LICENSE
  summary: piscem is a next-generation compacted colored de Bruijn Graph-based indexer and mapper

extra:
  skip-lints:
    - uses_vcs_url
