package:
  name: perl-getopt-long
  version: "2.57"

source:
  url: https://cpan.metacpan.org/authors/id/J/JV/JV/Getopt-Long-2.57.tar.gz
  sha256: d3791e6bf167708364ea5ad3be578dc9173a0076167160a4341c05a1e979795e

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl

  run:
    - perl

test:
  imports:
    - Getopt::Long

about:
  home: http://metacpan.org/pod/Getopt::Long
  license: unknown
  summary: 'Module to handle parsing command line options'
