package:
  name: perl-getopt-long
  version: "2.55"

source:
  url: https://cpan.metacpan.org/authors/id/J/JV/JV/Getopt-Long-2.55.tar.gz
  sha256: a7198a21da455c1c2349551dcc0252332d84ebdfa2c0d2e2bf11d2586f5b3fba

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl

  run:
    - perl

test:
  imports:
    - Getopt::Long

about:
  home: http://metacpan.org/pod/Getopt::Long
  license: unknown
  summary: 'Module to handle parsing command line options'
