{% set name = "metabolabpy" %}
{% set version = "0.8.14" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "98ceb6740de03837c1b3be26d4d737a0760a78e32538c65fd203fc664f4efca0"

build:
  noarch: python
  number: 0
  entry_points:
    - metabolabpy = metabolabpy.__main__:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python >3.7
    - pip
  run:
    - python >3.7
    - numpy
    - scipy
    - matplotlib-base
    - pyside2
    - openpyxl
    - pyautogui
    - qtmodern
    - xlsxwriter

test:
  imports:
    - metabolabpy
    - metabolabpy.nmr
  commands:
    - metabolabpy --help

about:
  home: https://github.com/ludwigc/metabolabpy
  license: GNU General Public v3 (GPLv3)
  license_family: GPL3"
  license_file: LICENSE
  summary: "Python package for data processing of NMR 1D and 2D metabolomics and metabolism tracing data"

extra:
  container:
    extended-base: true
  recipe-maintainers:
    - RJMW
    - ludwigc
