{% set name = "perl-file-copy-recursive-reduced" %}
{% set version = "0.007" %}
{% set sha256 = "d3b58522e69803a91437e29c099eb706e8373f1eef0518a4dc3669dd3dfcdc27" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/J/JK/JKEENAN/File-Copy-Recursive-Reduced-0.007.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-file-path
    - perl-test-simple
    - perl-capture-tiny
    - perl-file-temp
    - perl-path-tiny
    - perl-extutils-makemaker

  run:
    - perl
    - perl-file-path

test:
  imports:
    - File::Copy::Recursive::Reduced

about:
  home: http://thenceforward.net/perl/modules/File-Copy-Recursive-Reduced/
  license: perl_5
  summary: 'Recursive copying of files and directories within Perl 5 toolchain'
