{% set name = "perl-term-table" %}
{% set version = "0.018" %}
{% set sha256 = "9159b9131ee6b3f3956b74f45422985553574babbfaeba60be5c17bc114ac011" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/E/EX/EXODIST/Term-Table-0.018.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-module-build
    - perl-extutils-makemaker
    - perl-carp
    - perl-importer
    - perl-test-simple

  run:
    - perl
    - perl-carp
    - perl-importer

test:
  imports:
    - Term::Table
    - Term::Table::Cell
    - Term::Table::CellStack
    - Term::Table::LineBreak
    - Term::Table::Spacer
    - Term::Table::Util

about:
  home: http://metacpan.org/pod/Term::Table
  license: perl_5
  summary: 'Format a header and rows into a table'
