{% set name = "genmod" %}
{% set version = "3.8.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 72921cce29fd8d6b99eea76921a0a71d3846abcb92bcb02dafd24886ab9264a3

build:
  number: 0
  noarch: python
  run_exports:
    - {{ pin_subpackage('genmod', max_pin="x") }}
  entry_points:
    - genmod = genmod.commands.base:cli
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - click <7
    - configobj
    - extract_vcf >=0.4.2
    - interval_tree >=0.3.2
    - intervaltree
    - ped_parser >=1.6.2
    - pip
    - pytabix
    - pytest
    - python
  run:
    - click <7
    - configobj
    - extract_vcf >=0.4.2
    - interval_tree >=0.3.2
    - intervaltree
    - ped_parser >=1.6.2
    - pytabix
    - pytest
    - python

test:
  imports:
    - genmod
    - genmod.annotate_models
    - genmod.annotate_models.models
    - genmod.annotate_regions
    - genmod.annotate_variants
    - genmod.annotations
    - genmod.commands
    - genmod.errors
    - genmod.score_variants
    - genmod.utils
    - genmod.vcf_tools
  commands:
    - genmod --help

about:
  home: "http://github.com/moonso/genmod"
  license: MIT
  license_family: MIT
  license_file: 
  summary: "Annotate genetic inheritance models in variant files"

extra:
  recipe-maintainers:
    - ramprasadn
