{% set name = "aeon" %}
{% set version = "0.3.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/sybila/biodivine-aeon-py/archive/refs/tags/{{ version }}.tar.gz"
  sha256: "70285c51b0d220d6a5edc4c0307d4bde2d7c4496c51cd85f8cefbf5a56087bff"

build:
  skip: true  # [py < 39]
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - maturin
  host:
    - pip
    - python
    - clangdev
  run:
    - python

test:
  imports:
    - biodivine_aeon

about:
  home: https://github.com/sybila/biodivine-aeon-py
  license: MIT License
  license_family: MIT
  license_file: LICENSE
  summary: "Python/Rust library for symbolic manipulation of Boolean networks."
