{% set name = 'beast2' %}
{% set version = '2.7.5' %}
{% set hash = '5b1ea5a65fd4265e25d376c5be516d333fd8c89687d738c12c0c3e55272a1346' %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: https://github.com/CompEvol/beast2/archive/v{{ version }}.zip
  sha256: '{{ hash }}'
  patches:
    #- build.patch
    - beast_lib.patch
    - citation.patch

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - gettext
    - openjdk
    - ant
  host:
    - openjdk 8.0* zulu8*
    - beagle-lib
    - fontconfig
    - font-ttf-ubuntu
    - fontconfig
    - freetype
    - xorg-libxtst
  run:
    - openjdk 8.0* zulu8*
    - beagle-lib
    - fontconfig
    - font-ttf-ubuntu
    - fontconfig
    - freetype
    - xorg-libxtst

test:
  commands:
    - beast -version
    # check to make sure beagle-lib is loaded ok
    - beast -beagle_info \| grep Flags
    - applauncher -help
    - packagemanager -help
    - loganalyser -h
    - logcombiner -help
    - treeannotator -help

about:
  home: http://www.beast2.org
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: "BEAST 2 is a cross-platform program for Bayesian phylogenetic analysis of molecular sequences."
