package:
  name: fwdpy11
  version: "0.22.1"

source:
  url: https://files.pythonhosted.org/packages/e5/76/168c1cccd632ebf2208c7ccf032d29d524b4719d5687576a5c621f29af88/fwdpy11-0.22.1.tar.gz
  sha256: 17dfa10009d506446308a4cb85a5a2a66831343439e10c2d103af1fd086a7405

build:
  skip: True # [py27 or py<38]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pkgconfig
    - python
    - pip
    - numpy >=1.20
    - pybind11 ==2.10.0
    - tskit >=0.5
    - gsl
    - openblas
    - attrs
    - setuptools_scm
    - rust >=1.62.1  
#    - intervaltree
#    - pybind11 >=2.10.0
#    - numpy
#    - scipy
#    - attrs >=0.19.2
#    - black
#    - tskit
#    - msprime
#    - gsl
#    - boost
#    - pytest
#    - pytest-xdist
#    - setuptools_scm
#    - demes >=0.2.0
#    - rust >=1.62.1
#    - hypothesis
  run:
    - python
    - numpy >=1.20
    - tskit >=0.5
    - gsl
    - openblas
    - scipy
    - attrs
    - black
    - demes >=0.2
    - intervaltree

test:
  # Python imports
  imports:
    - fwdpy11

about:
  home: http://pypi.python.org/pypi/fwdpy11
  license: GNU General Public License v3 or later (GPLv3+)
  license_file: "COPYING"
  summary: 'Forward-time population genetic simulation in Python.'

extras:
  identifiers:
    - 10.1534/genetics.114.165019
    - 10.1371/journal.pcbi.1006581
