package:
  name: perl-sereal-encoder
  version: "5.001"

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Encoder-5.001.tar.gz
  sha256: 2367f2f5f1486f32f65c3905048918de55639c79d1835ab56789f70cedfbbac3

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-scalar-list-utils
    - perl-extutils-makemaker
    - perl-file-path
    - perl-pathtools
    - perl-test-longstring
    - perl-extutils-parsexs
    - perl-test-warn
    - perl-test-simple
    - perl-sereal-decoder >=4.002

  run:
    - perl

test:
  imports:
    - Sereal::Encoder
    - Sereal::Encoder::Constants

about:
  home: http://metacpan.org/pod/Sereal::Encoder
  license: perl_5
  summary: 'Fast, compact, powerful binary serialization'
