{% set name = "perl-module-corelist" %}
{% set version = "5.20220920" %}
{% set sha256 = "fb07a92689ebd2cf711b3455b5ea01d7a5cf8cec1f1c0a366106abd6a981321d" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Module-CoreList-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-version
    - perl-extutils-makemaker
  run:
    - perl
    - perl-version

test:
  imports:
    - Module::CoreList
    - Module::CoreList::Utils

about:
  home: https://metacpan.org/pod/Module::CoreList
  license: perl_5
  summary: 'what modules shipped with versions of perl'
