{% set version = "0.12.3" %}
{% set name = "sequana_pipetools" %}
{% set sha = "49de96e922c2017edd695811439b984d659270d77c3ddc9c7cdc4b8f53382006" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: 0
  entry_points:
    - sequana_completion=sequana_pipetools.completion:main
    - sequana_slurm_status=sequana_pipetools.slurm:main
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python <3.10
    - setuptools
    - pip
  run:
    - python <3.10
    - deprecated
    - easydev
    - parse
    - ruamel.yaml
    - pykwalify
    - importlib_resources
    - pyyaml
    - aiohttp
    - tqdm

test:
  imports:
    - sequana_pipetools
  commands:
    - sequana_completion --help 1>out 2>err
    - sequana_slurm_status --help 1>out 2>err


about:
  home: "https://github.com/sequana/sequana_pipetools"
  license: "BSD 3-clause"
  summary: "A set of tools to help building or using Sequana pipelines"
  license_family: BSD

extra:
  recipe-maintainers: 
    - cokelaer
  skip-lints:
    - uses_setuptools
