{% set version = "0.13.0" %}
{% set name = "sequana_pipetools" %}
{% set sha = "e284278e2f97e405dc341f86ffebbffc71fce713fa7fb7104d7ea9faae703793" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: 0
  entry_points:
    - sequana_completion=sequana_pipetools.completion:main
    - sequana_slurm_status=sequana_pipetools.slurm:main
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
    - poetry
  run:
    - python >=3.8
    - deprecated >=1.2.13
    - easydev >=0.12.1
    - parse >=1.19
    - ruamel.yaml >=0.17.32
    - pykwalify >=1.8
    - importlib_resources >=5.4
    - pyyaml >=1.3
    - aiohttp >=3.8.4
    - tqdm >=4.65
    - packaging >=23.1
    - charset-normalizer 2.*

test:
  imports:
    - sequana_pipetools
  commands:
    - sequana_completion --help 1>out 2>err
    - sequana_slurm_status --help 1>out 2>err


about:
  home: "https://github.com/sequana/sequana_pipetools"
  license: "BSD 3-clause"
  summary: "A set of tools to help building or using Sequana pipelines"
  license_family: BSD

extra:
  recipe-maintainers: 
    - cokelaer
  skip-lints:
    - uses_setuptools
