{% set name = "perl-ffi-checklib" %}
{% set version = "0.29" %}
{% set sha256 = "87e9fdde3c02a864ac6febabfac24a679d53bb250c46fb0583626607880b643c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/FFI-CheckLib-0.29.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-test2-suite
  run:
    - perl

test:
  imports:
    - FFI::CheckLib

about:
  home: https://metacpan.org/pod/FFI::CheckLib
  license: perl_5
  summary: 'Check that a library is available for FFI'
