{% set name = "perl-ffi-checklib" %}
{% set version = "0.30" %}
{% set sha256 = "9551947cd011fb0e5675e3eaada9629758a58bce2d01070cc55f8fab9484d73e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PL/PLICEASE/FFI-CheckLib-0.30.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - make
  host:
    - perl
    - perl-test2-suite
  run:
    - perl

test:
  imports:
    - FFI::CheckLib

about:
  home: https://metacpan.org/pod/FFI::CheckLib
  license: perl_5
  summary: 'Check that a library is available for FFI'
