{% set name = "firecloud" %}
{% set version = "0.16.36" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 14433cca4ab264470d941b15adc26cb0a4fdb994634158ffba846c7ab77d053d

build:
  number: 0
  noarch: python
  entry_points:
    - fissfc = firecloud.fiss:main_as_cli
  run_exports:
    - {{ pin_subpackage(name, max_pin="x.x") }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - google-auth >=1.6.3
    - google-cloud-storage
    - pydot
    - python
    - requests
    - six

test:
  imports:
    - firecloud
  commands:
    - fissfc --help

about:
  home: https://github.com/broadinstitute/fiss
  license: BSD-3-Clause
  license_family: BSD
  summary: API and CLI for Broad Institute's Firecloud workspace/workflow management service
  doc_url: https://software.broadinstitute.org/firecloud/
  dev_url: https://github.com/broadinstitute/fiss

extra:
  recipe-maintainers:
    - notestaff
