{% set version = "3.3" %}
{% set sha256 = "290df227c91b15ef3c932cf66b2c7cd52c617071233a7957ca7e6e54889e2b79" %}

package:
  name: hmftools-sage
  version: '{{ version }}'

source:
  url: 'https://github.com/hartwigmedical/hmftools/releases/download/sage-v{{ version }}/sage_v{{ version }}.jar'
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - zlib
    - openjdk >=8
    - bioconductor-variantannotation
    - bioconductor-genomicranges
    - r-dplyr
    - r-tidyr
    - r-ggplot2
    - xorg-libxt
    - font-ttf-dejavu

test:
  commands:
    - 'SAGE 2>&1 | grep -q "Sage version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/sage
  license: GPL-3.0-only
  license_family: GPL
  summary: SAGE is a somatic SNV, MNV and small INDEL caller optimised to call narrow regions of the genome with high prior chance of a variant with very high sensitivity.
