{% set name = "perl-experimental" %}
{% set version = "0.031" %}
{% set sha256 = "7c6803ea96dadcfaf9d800bfaeedfd165bf4155199e80054473bd677269d7e35" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/L/LE/LEONT/experimental-0.031.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-carp
    - perl-extutils-makemaker
    - perl-version

  run:
    - perl
    - perl-carp
    - perl-version

test:
  imports:
    - experimental

about:
  home: http://metacpan.org/pod/experimental
  license: perl_5
  summary: 'Experimental features made easy'
