{% set version="2.7.1" %}
package:
  name: arvados-cwl-runner
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/a/arvados-cwl-runner/arvados-cwl-runner-{{ version }}.tar.gz
  sha256: 53a56e4f1f8e8dc2aa8270bf5533e1ec538525ce08353e0b834e7df4cb116868

build:
  noarch: python
  number: 0
  run_exports:
    - {{ pin_subpackage("arvados-cwl-runner", max_pin="x.x") }}

requirements:
  host:
    - pip
    - python
  run:
    - python
    - ruamel.yaml >=0.15.54
    - cwltool >=3.1
    - schema-salad >=3.0.20181129082112
    - arvados-python-client >=2.6

test:
  imports:
    - arvados_cwl

about:
  home: https://github.com/curoverse/arvados/tree/master/sdk/cwl
  license: Apache 2.0
  summary: 'Arvados Common Workflow Language runner'
