# .circleci/config.yml
version: 2.1

executors:
  # osx-arm64:
  #   macos:
  #     xcode: 14.2.0 # indicate your selected version of Xcode
  #   resource_class: macos.m1.large.gen1
  linux-aarch64:
    docker:
      - image: cimg/base:2023.06
    resource_class: arm.medium

jobs: # a basic unit of work in a run
  build_and_test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout

      - run:
          name: Fetch bioconda install script
          command: wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/{common,install-and-set-up-conda,configure-conda}.sh

      - restore_cache:
          keys:
            - bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}-{{ checksum "configure-conda.sh" }}-{{ checksum "common.sh" }}

      - run:
          name: Install bioconda-utils
          command: |
            sudo mkdir -p /opt/
            sudo chmod o+rwx /opt
            bash install-and-set-up-conda.sh

      - save_cache:
          key: bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}-{{ checksum "configure-conda.sh" }}-{{ checksum "common.sh" }}
          paths:
            - /opt/mambaforge/
    
      - run:
          name: Setup PATH
          command:
            echo 'export PATH=/opt/mambaforge/bin:"$PATH"' >> "$BASH_ENV"

      # We reconfigure conda to use the right channel setup.
      # This has to be done after the cache is restored, because
      # the channel setup is not cached as it resides in the home directory.
      # We could use a system-wide (and therefore cached) channel setup,
      # but mamba does not support that at the time of implementation
      # (it ignores settings made by --system).
      - run:
          name: Configure conda
          command: bash configure-conda.sh

      - run:
          name: Build and test
          command: |
            source /opt/mambaforge/etc/profile.d/conda.sh
            source /opt/mambaforge/etc/profile.d/mamba.sh
            mamba activate bioconda
            bioconda-utils build recipes config.yml --git-range origin/master HEAD

      - run:
          name: Prepare artifacts
          command: |
            (
            mkdir -p /tmp/artifacts/packages
            cd /opt/mambaforge/envs/bioconda/conda-bld || exit 0
            find -name .cache | xargs rm -rf || true
            for n in index.html channeldata.json linux-aarch64 linux-64 osx-64 noarch; do
              cp -rv $n /tmp/artifacts/packages || true
            done
            ) || true

      - store_artifacts:
          path: /tmp/artifacts

  build_and_upload:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    steps:
      - checkout

      - run:
          name: Fetch bioconda install script
          command: wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/{common,install-and-set-up-conda,configure-conda}.sh

      - restore_cache:
          keys:
            - bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}-{{ checksum "configure-conda.sh" }}-{{ checksum "common.sh" }}

      - run:
          name: Install bioconda-utils
          command: |
            sudo mkdir -p /opt
            sudo chmod o+rwx /opt
            bash install-and-set-up-conda.sh

      - save_cache:
          key: bioconda-utils-{{ arch }}-{{ checksum "install-and-set-up-conda.sh" }}-{{ checksum "configure-conda.sh" }}-{{ checksum "common.sh" }}
          paths:
            - /opt/mambaforge

      - run:
          name: Setup PATH
          command:
            echo 'export PATH=/opt/mambaforge/bin:"$PATH"' >> "$BASH_ENV"

      # We reconfigure conda to use the right channel setup.
      # This has to be done after the cache is restored, because
      # the channel setup is not cached as it resides in the home directory.
      # We could use a system-wide (and therefore cached) channel setup,
      # but mamba does not support that at the time of implementation
      # (it ignores settings made by --system).
      - run:
          name: Configure conda
          command: bash configure-conda.sh

      - run:
          name: Build and push
          command: |
            source /opt/mambaforge/etc/profile.d/conda.sh
            source /opt/mambaforge/etc/profile.d/mamba.sh
            mamba activate bioconda
            # TODO we need to update bioconda-utils with support for retrieving circleci artifacts from above
            bioconda-utils handle-merged-pr recipes config.yml \
              --repo bioconda/bioconda-recipes \
              --git-range ${CIRCLE_SHA1}~1 ${CIRCLE_SHA1} \
              --fallback build

  bulk_build:
    parameters:
      os:
        type: executor
      runner:
        type: integer
    executor: << parameters.os >>
    # strategy:
    #   fail-fast: false
    steps:
        #   - uses: actions/checkout@v3
        # with:
        #   # checkout as bioconda-bot in order to have the permission to push fail logs
        #   token: ${{secrets.BIOCONDA_BOT_REPO_TOKEN}}
      - checkout

      - run:
          name: Check for [ci run]
          command: |
            commit_message="$(git log --format=oneline -n 1 $CIRCLE_SHA1)"
            if [[ $commit_message  =~ "[ci run]" ]]; then
              echo "[ci run] found, continuing."
            else
              echo "[ci run] not found, exiting."
              circleci-agent step halt
            fi

      - run:
          name: set git user
          command: |
            git config user.name bioconda-bot
            git config user.email bioconda-bot@users.noreply.github.com

      - run:
          name: Fetch bioconda install script
          command: wget https://raw.githubusercontent.com/bioconda/bioconda-common/master/{common,install-and-set-up-conda,configure-conda}.sh

      - restore_cache:
          keys:
            - bioconda-utils-{{ arch }}-bulk--{{ checksum "install-and-set-up-conda.sh" }}-{{ checksum "configure-conda.sh" }}-{{ checksum "common.sh" }}

      - run:
          name: Install bioconda-utils
          command: |
            sudo mkdir -p /opt/
            sudo chmod o+rwx /opt
            bash install-and-set-up-conda.sh

      - save_cache:
          key: bioconda-utils-{{ arch }}--bulk--{{ checksum "install-and-set-up-conda.sh" }}-{{ checksum "configure-conda.sh" }}-{{ checksum "common.sh" }}
          paths:
            - /opt/mambaforge/
    
      - run:
          name: Setup PATH
          command:
            echo 'export PATH=/opt/mambaforge/bin:"$PATH"' >> "$BASH_ENV"

      # We reconfigure conda to use the right channel setup.
      # This has to be done after the cache is restored, because
      # the channel setup is not cached as it resides in the home directory.
      # We could use a system-wide (and therefore cached) channel setup,
      # but mamba does not support that at the time of implementation
      # (it ignores settings made by --system).
      - run:
          name: Configure conda
          command: bash configure-conda.sh

      # setup Docker to use for --docker and --mulled-test
      - setup_remote_docker:
          version: default

      # FIXME: For initial testing, the following were removed: --anaconda-upload --mulled-upload-target biocontainers --record-build-failures  
      # TODO: Make --docker-base-image dynamic based on arch?
      - run:
          name: Build and upload
          command: |
            source /opt/mambaforge/etc/profile.d/conda.sh
            source /opt/mambaforge/etc/profile.d/mamba.sh
            mamba activate bioconda
            echo '============'
            conda info --all
            conda config --show-sources
            python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
            echo '============'
            bioconda-utils build recipes config.yml \
              --worker-offset << parameters.runner >> --n-workers 6 \
              --docker --mulled-test --docker-base-image quay.io/bioconda/bioconda-utils-build-env-cos7-aarch64 \
              --skiplist-leafs
            conda clean -y --all

      # Debugging script error
      - run:
          name: Prepare artifacts
          when: always
          command: |
            mkdir -p /tmp/artifacts/debug
            for n in /tmp/*/build_script.bash; do
              cp -rv $n /tmp/artifacts/debug || true
            done

      - store_artifacts:
          path: /tmp/artifacts


workflows:
  build and test (ARM):
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: master
          matrix:
            parameters:
              os:
                #- osx-arm64
                - linux-aarch64

  build and upload (ARM):
    jobs:
      - build_and_upload:
          filters:
            branches:
              only: master
          matrix:
            parameters:
              os:
                #- osx-arm64
                - linux-aarch64

  Bulk branch (ARM):
    jobs:
      - bulk_build:
          filters:
            branches:
              only: bulk-arm-builds
              # for testing
          matrix:
            parameters:
              os: 
                #- osx-arm64
                - linux-aarch64
              runner: [0, 1, 2, 3, 4, 5]
