{% set version = "1.7" %}
{% set sha256 = "044751b3b12591fa43252eb7797bf2d07982d30e6e029954c9df7264a4bb1d6a" %}

package:
  name: hmftools-isofox
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/isofox-v{{ version }}/isofox_v{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('hmftools-isofox', max_pin="x.x") }}

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - 'isofox 2>&1 | grep -q "Isofox version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/isofox
  license: GPL-3.0-only
  license_family: GPL
  summary: 'Isofox is a tool for counting fragment support for identifying and counting gene and transcript features using genome aligned RNASeq data in tumor samples.'
