package:
  name: hgtools
  version: "9.2.0"

source:
  url: https://files.pythonhosted.org/packages/78/ba/48e8df1402be5c40b49fb0ed76ae72e9343ab33e47feac0d0015a4f21e57/hgtools-9.2.0.tar.gz
  sha256: eccd7d92882acdb3d22d0aeca3f0f789f0bcaa67a33c32541f97bc8ddc75581b

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - packaging
  run:
    - python >=3.6
    - backports.unittest_mock
    - packaging

test:
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests

about:
  home: https://github.com/jaraco/hgtools
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial and Git repositories'
