package:
  name: hgtools
  version: "10.0.0"

source:
  url: https://files.pythonhosted.org/packages/22/2c/f4e8fc5e213fef932cfb03a55ecabfa061a64e1a8686db9ec79dc015212f/hgtools-10.0.0.tar.gz
  sha256: cf98dbb1466941b7ab799200a4b18569f17706e5fb5364b01b16ff541157623c

build:
  number: 0
  noarch: python
  preserve_egg_dir: True
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - setuptools_scm
    - packaging
  run:
    - python >=3.6
    - backports.unittest_mock
    - packaging

test:
  imports:
    - hgtools
    - hgtools.managers
    - hgtools.tests

about:
  home: https://github.com/jaraco/hgtools
  license: GNU General Public License (GPL)
  summary: 'Classes and setuptools plugin for Mercurial and Git repositories'
