{% set name = "perl-datetime" %}
{% set version = "1.63" %}
{% set sha256 = "1b11e49ec6e184ae2a10eccd05eda9534f32458fc644c12ab710c29a3a816f6f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/DateTime-1.63.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-extutils-makemaker
    - perl-namespace-autoclean
    - perl-test-more
    - perl-test-warnings
    - perl-try-tiny
    - perl-warnings-register
    - perl-cpan-meta-check
    - perl-test-fatal
    - perl-specio
    - perl-variable-magic
    - perl-datetime-locale
    - perl-datetime-timezone >=2.44
    - perl-params-validationcompiler >=0.26
    - perl-test-without-module
  run:
    - perl
    - perl-namespace-autoclean
    - perl-try-tiny
    - perl-warnings-register
    - perl-cpan-meta-check
    - perl-test-fatal
    - perl-specio
    - perl-datetime-locale
    - perl-datetime-timezone >=2.44
    - perl-params-validationcompiler >=0.26
    - perl-test-without-module

test:
  imports:
    - DateTime
    - DateTime::Duration

about:
  home: http://metacpan.org/release/DateTime
  license: artistic_2
  summary: 'A date and time object for Perl'
