{% set version = "1.2.2" %}
{% set sha256 = "3f5a258425d5c7cc28a7ff4961175d7da7e80aaada4287b2462dff33d4ff520a" %}

package:
  name: hmftools-sv-prep
  version: '{{ version }}'

source:
  url: 'https://github.com/hartwigmedical/hmftools/releases/download/sv-prep-v{{ version }}/sv-prep_v{{ version }}.jar'
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - zlib
    - openjdk >=8
    - samtools

test:
  commands:
    - 'SvPrep 2>&1 | grep -q "SvPrep version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/sv-prep
  license: GPL-3.0-only
  license_family: GPL
  summary: SV Prep generates a maximally filtered SV BAM file by identifying candidate SV junctions and extracting all reads that may provide support to that junction.
