{% set name = "perl-term-detect-software" %}
{% set version = "0.224" %}
{% set sha256 = "d08ee99acfa2bb9a5552efea74d73e393f4cfc69495b2a00ed3856d99b039248" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/P/PE/PERLANCAR/Term-Detect-Software-0.224.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-experimental
    - perl-perl-osnames >=0.09
    - perl-file-which
    - perl-extutils-makemaker

  run:
    - perl
    - perl-experimental
    - perl-file-which

test:
  imports:
    - Term::Detect::Software

about:
  home: https://metacpan.org/release/Term-Detect-Software
  license: perl_5
  summary: 'Detect terminal (emulator) software and its capabilities'
