{% set version = "1.1.1" %}

package:
  name: tabixpp
  version: {{ version }}

source:
  url: https://github.com/ekg/tabixpp/archive/v{{version}}.tar.gz
  sha256: 82a956763c85e251374743f2f6fa343f0c50d9f0f600ba3dee9887967d58d3fb
  patches:
    - shared_lib.patch
    - pkg-config.patch

build:
  number: 13

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - zlib
    - bzip2
    - xz
    - htslib
    - bc
    - samtools
    - pkg-config #needed for MacOS build
    
  run:
    - zlib
    - bzip2
    - xz
    - htslib
    - bc
    - samtools
    
test:
  commands:
    - which tabix++
    

about:
  home: https://github.com/ekg/tabixpp
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: This is a C++ wrapper around tabix project which abstracts some of the details of opening and jumping in tabix-indexed files.
  maintainers: jpuritz

extra:
   identifiers:
    - biotools:tabixpp
