{% set version = "1.15.2" %}
{% set sha256 = "5f35bd500c4de393a7771d506762939776242d9cf05a6335e0ce94bce0e8bd10" %}

package:
  name: hmftools-cobalt
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/cobalt-v{{ version }}/cobalt-{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk >=8
    - bioconductor-copynumber
    - r-dplyr

test:
  commands:
    - 'COBALT 2>&1 | grep -q "tumor_bam"'

about:
  home: https://github.com/hartwigmedical/hmftools/blob/master/cobalt/README.md
  license: MIT
  license_family: MIT
  summary: Counts read starts within each 1000 base window to use in PURPLE
