{% set name = "perl-http-message" %}
{% set version = "6.39" %}
{% set sha256 = "e0498fab85853f8361cc22d5cb83c9c3d4d3ab425de6815bbcfca0a83a498fbd" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SI/SIMBABQUE/HTTP-Message-6.39.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-encode-locale
    - perl-storable
    - perl-exporter
    - perl-carp
    - perl-io-html
    - perl-compress-raw-zlib
    - perl-uri
    - perl-mime-base64
    - perl-try-tiny
    - perl-http-date
    - perl-base
    - perl-lwp-mediatypes
    - perl-encode
    - perl-extutils-makemaker
    - perl-time-local
    - perl-url-encode
    - perl-file-temp
    - perl-lib
    - perl-uri
  run:
    - perl
    - perl-encode-locale
    - perl-file-spec
    - perl-exporter
    - perl-carp
    - perl-io-html
    - perl-compress-raw-zlib
    - perl-uri
    - perl-mime-base64
    - perl-http-date
    - perl-base
    - perl-lwp-mediatypes
    - perl-encode >=3.01
    - perl-url-encode

test:
  imports:
    - HTTP::Config
    - HTTP::Headers
    - HTTP::Headers::Auth
    - HTTP::Headers::ETag
    - HTTP::Headers::Util
    - HTTP::Message
    - HTTP::Request
    - HTTP::Request::Common
    - HTTP::Response
    - HTTP::Status

about:
  home: https://github.com/libwww-perl/HTTP-Message
  license: perl_5
  summary: 'HTTP style message (base class)'
