{% set name = "aspera-cli" %}
{% set version = "4.15.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  - url: https://github.com/IBM/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1c153723c3f6f444bd75d5ad9c91a4e8d86d15cbe5fb59cb56c318096c2296c6

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('aspera-cli', max_pin="x") }}

requirements:
  build:
    - ruby >=3
  host:
    - ruby >=3
  run:
    - ruby >=3

test:
  commands:
    - ascli -h
    - ascp -h

about:
  home: https://github.com/IBM/aspera-cli
  license: Apache-2.0
  license_file: 
    - LICENSE
    - aspera-license
  summary: "Command Line Interface for IBM Aspera products"
  dev_url: https://github.com/IBM/aspera-cli

extra:
  recipe-maintainers:
    - farchaab
