{% set version = "1.15.0" %}
{% set name = "OmicsLonDA" %}
{% set bioc = "3.17" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  md5: 32f03387aa3f1f0f1567c1e06f978f41
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, testthat, devtools, BiocManager
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.46.0,<0.47.0'
    - 'bioconductor-biocparallel >=1.34.0,<1.35.0'
    - 'bioconductor-summarizedexperiment >=1.30.0,<1.31.0'
    - r-base
    - r-ggplot2
    - r-gss
    - r-plyr
    - r-pracma
    - r-zoo
  run:
    - 'bioconductor-biocgenerics >=0.46.0,<0.47.0'
    - 'bioconductor-biocparallel >=1.34.0,<1.35.0'
    - 'bioconductor-summarizedexperiment >=1.30.0,<1.31.0'
    - r-base
    - r-ggplot2
    - r-gss
    - r-plyr
    - r-pracma
    - r-zoo
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'Omics Longitudinal Differential Analysis'
  description: 'Statistical method that provides robust identification of time intervals where omics features (such as proteomics, lipidomics, metabolomics, transcriptomics, microbiome, as well as physiological parameters captured by wearable sensors such as heart rhythm, body temperature, and activity level) are significantly different between groups.'
  license_file: LICENSE

