{% set version = "1.711" %}
package:
  name: perl-log-any
  version: "1.711"

source:
  url: https://cpan.metacpan.org/authors/id/P/PR/PREACTION/Log-Any-{{ version }}.tar.gz
  sha256: b4578e936b844af49906e10c1a59e1c961995de340b1c812891713121233f767

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-pathtools
    - perl-apache-test
    - perl-test-simple
    - perl-extutils-makemaker
      # - perl-exporter
      # - perl-constant
      # - perl-carp
      # - perl-data-dumper
      # - perl-io

  run:
    - perl
    - perl-apache-test
    - perl-test-simple
    #- perl-exporter
    #- perl-constant
    #- perl-carp
    #- perl-data-dumper
    #- perl-io

test:
  imports:
    - Log::Any
    - Log::Any::Adapter
    - Log::Any::Adapter::Base
    - Log::Any::Adapter::File
    - Log::Any::Adapter::Null
    - Log::Any::Adapter::Stderr
    - Log::Any::Adapter::Stdout
    - Log::Any::Adapter::Test
    - Log::Any::Adapter::Util
    - Log::Any::Manager
    - Log::Any::Proxy
    - Log::Any::Proxy::Null
    - Log::Any::Proxy::Test
    - Log::Any::Test

about:
  home: https://github.com/preaction/Log-Any
  license: perl_5
  summary: 'Bringing loggers and listeners together'
