package:
  name: perl-extutils-manifest
  version: "1.74"

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/ExtUtils-Manifest-1.74.tar.gz
  sha256: 0c4d819fb9fcda40cea83c22c5c03fc57bff96233b0106fd52a540d2bd8639cf

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl

  run:
    - perl

test:
  imports:
    - ExtUtils::Manifest

about:
  home: https://metacpan.org/release/ExtUtils-Manifest
  license: perl_5
  summary: 'Utilities to write and check a MANIFEST file'
