{% set version = "0" %}

package:
  name: r-cdseq
  version: {{ version }}

source:
  # No tagged releases for some reason
  url: https://github.com/omnideconv/CDSeq/archive/d5e776a7d161e59e0844245c23a231916fb6602f.zip
  sha256: def178efff98e832f6a3897650ff9ae5306c8fee75545a9e21ba61058f6c5700

build:
  # no r-harmony on OSX
  skip: True  # [osx]
  number: 5
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - r-base
    - r-roxygen2 >=6.0.1
    - r-rcpp >=1.0.3
    - r-mass
    - r-foreach
    - r-doparallel
    - r-dirmult
    - r-rcppthread
    - r-iterators
    - r-seurat
    - r-ggplot2
    - r-magrittr
    - r-dplyr
    - r-rlang
    - r-matrix
    - r-matrixstats
    - r-ggpubr
    - r-pheatmap
    - r-harmony
    - r-gplots
    - r-clue
    - bioconductor-biobase
    - r-qlcmatrix
  run:
    - r-base
    - r-rcpp >=1.0.3
    - r-mass
    - r-foreach
    - r-doparallel
    - r-dirmult
    - r-rcppthread
    - r-iterators
    - r-seurat
    - r-ggplot2
    - r-magrittr
    - r-dplyr
    - r-rlang
    - r-matrix
    - r-matrixstats
    - r-ggpubr
    - r-pheatmap
    - r-harmony
    - r-gplots
    - r-clue
    - bioconductor-biobase
    - r-qlcmatrix

test:
  commands:
    - $R -e "library('CDSeq')"

about:
  home: https://github.com/omnideconv/CDSeq
  license: GPL-3
  summary: "Estimate cell-type-specific gene expression profiles and sample-specific cell-type proportions simultaneously using bulk sequencing data. Kang et al. (2019) <doi:10.1371/journal.pcbi.1007510>."
  license_family: GPL
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - LorenzoMerotto
    - grst
  identifiers:
    - doi:10.1371/journal.pcbi.1007510
