{% set package = "ucsc-bed-tools" %}
{% set version = "454" %}
{% set sha256 = "dd547be640684982b27e419fa891d359d0693fbcf2f36d57b4a916939d31f1a7" %}

package:
  name: {{ package }}
  version: {{ version }}

source:
  url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.archive/userApps.v{{ version }}.src.tgz"
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]
  binary_relocation: False
  run_exports:
    - {{ pin_subpackage("ucsc-bed-tools", max_pin="x") }}
  #ignore_run_exports:
    #- libpng
    #- libuuid

requirements:
  build:
    - rsync
    #- make
    #- {{ compiler('c') }}
    #- {{ compiler('cxx') }}
    #- binutils # [linux]
  host:
    #- libpng
    #- libuuid
    #- mysql-connector-c
    #- openssl
    #- libopenssl-static
    #- zlib
  run:
    #- libpng
    #- libuuid
    #- mysql-connector-c
    #- openssl

test:
  commands:
    - which bedClip
    - which bedCommonRegions
    - which bedCoverage
    - which bedExtendRanges
    - which bedGraphPack
    - which bedGeneParts
    - which bedIntersect
    - which bedGraphToBigWig
    - which bedJoinTabOffset
    - which bedItemOverlapCount
    - which bedJoinTabOffset.py
    - which bedMergeAdjacent
    - which bedPileUps
    - which bedPartition
    - which bedRemoveOverlap
    - which bedSort
    - which bedToExons
    - which bedToBigBed
    - which bedRestrictToPositions
    - which bedToGenePred
    - which bedToPsl
    - which bedWeedOverlapping
    - which bigBedNamedItems
    - which bigBedInfo
    - which bigBedToBed
    - which bigBedSummary
    - which bigBedToBed
    - which fixStepToBedGraph.pl
    - which genePredToBed
    - which bigWigToBedGraph
    - which netToBed
    - which varStepToBedGraph.pl
    - which pslToBed
    - which vcfToBed

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  description: 'A package containing any UCSC kent tools matching the following globs: bed*, bigBed*, *ToBed*'
  summary: "All of the ucsc kent tools"

extra:
  skip-lints:
    # repackaged binary
    - should_be_noarch_generic
