{% set name = "IPK" %}
{% set version = "0.4.0" %}
{% set sha256 = "0e2c2cf923c15caf35cc526156e53501fdd68874102e1a7be6d48f23fef8db60" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/phylo42/IPK/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: generic

requirements:
  build:
    - cmake
    - make
    - boost
    - zlib
    - {{ compiler('cxx') }}
  host:
    - zlib
    - boost
    - python
  run:
    - boost
    - python
    - raxml-ng
    - phyml

test:
  commands:
    - python ipk.py --help

about:
  home: https://github.com/phylo42/IPK
  license_file: LICENSE
  license: MIT
  summary: IPK is a tool for computing phylo-k-mers for a fixed phylogeny.
