{% set version = "1.5.2" %}
{% set sha256 = "576532f225f890a5bf441a4266644b9c182e524c7f4f1c8df756a413142aa203" %}

package:
  name: hmftools-lilac
  version: '{{ version }}'

source:
  url: 'https://github.com/hartwigmedical/hmftools/releases/download/lilac-v{{ version }}/lilac_v{{ version }}.jar'
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('hmftools-lilac', max_pin="x") }}

requirements:
  run:
    - zlib
    - openjdk >=8

test:
  commands:
    - 'LILAC 2>&1 | grep -q "LilacApplication"'

about:
  home: https://github.com/hartwigmedical/hmftools
  license:  "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  summary: LILAC is a WGS tool to determine HLA Class I types.
