package:
  name: perl-sereal-decoder
  version: "5.001"

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-Decoder-5.001.tar.gz
  sha256: b27c33ec910de57d72817cc2baa0bf039d5e647a7359edfcf1cf7d5efeeed9b2

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
  host:
    - perl
    - perl-file-path
    - perl-test-warn
    - perl-test-simple
    - perl-extutils-makemaker
    - perl-test-longstring
    - perl-scalar-list-utils
    - perl-pathtools
    - perl-extutils-parsexs

  run:
    - perl

test:
  imports:
    - Sereal::Decoder
    - Sereal::Decoder::Constants
    - Sereal::Performance

about:
  home: http://metacpan.org/pod/Sereal::Decoder
  license: perl_5
  summary: 'Fast, compact, powerful binary deserialization'

