{% set version = "1.0" %}

package:
  name: mana
  version: {{ version }}

source:
  url: https://github.com/scchess/Mana/archive/refs/tags/{{ version }}.tar.gz
  sha256: 4c6146fb2869f22f4a42eb955f9ded9501297ac8ac7d14a70b0c3f51f95c324d

build:
  noarch: generic
  number: 1

requirements:
  run:
    - python >=3
    - samtools
    - bcftools
    - pysam
    - pysamstats
    - bedtools
    - minimap2
    - nanosim-h
    - numpy
    - pandas
    - tabulate
    - r-base
    - r-svglite
    - r-ggpubr

test:
  commands:
    - 

about:
  home: https://github.com/dpryan79/pyBigWig
  license: MIT
  license_file: LICENSE.txt
  summary: A python extension written in C for quick access to bigWig files.
