{% set version = "1.0.5" %}

package:
  name: vcflib
  version: {{ version }}

source:
  url: https://github.com/vcflib/vcflib/releases/download/v{{ version }}/vcflib-{{ version }}-src.tar.gz
  sha256: c864bfa53fb019090370f48ef5c2f5bec41518b3e48ef4e9de86506af0ee7d72
  patches:
    - shared_lib.patch
    - pkg-config.patch

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # python really only used as a build tool; no ${PREFIX}/bin/python needed.
    - python >=3
    - cmake
    - pkg-config
  host:
    - htslib
    - tabixpp
  run:
    - python >=3
    - zlib   
    - htslib
    - tabixpp

test:
  commands:
    - vcfallelicprimitives -h
    - vcffirstheader < /dev/null
    - vcfsort < /dev/null
    - vcfrandom | grep 'fileformat=VCF'

about:
  home: https://github.com/vcflib/vcflib
  license: MIT
  summary: Command-line tools for manipulating VCF files
  maintainers:
    - jpuritz
    - AndreaGuarracino

extra:
  identifiers:
    - biotools:vcflib
    - doi:10.1101/023754
