{% set name = "vcflib" %}
{% set version = "1.0.5" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  url: https://github.com/vcflib/{{ name }}/releases/download/v{{ version }}/vcflib-{{ version }}-src.tar.gz
  sha256: c864bfa53fb019090370f48ef5c2f5bec41518b3e48ef4e9de86506af0ee7d72
  #patches:
  #  - shared_lib.patch
  #  - pkg-config.patch

build:
  skip: True  # [osx]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - cmake
    - make
    # python really only used as a build tool; no ${PREFIX}/bin/python needed.
    - python >=3
    - pkg-config
    - tabixpp
    - zig
  host:
  python >=3
    - htslib
    - tabixpp
    - zig
  run:
    - python >=3
    - zlib   
    - htslib
    - tabixpp
    - zig

test:
  commands:
    - vcfallelicprimitives -h
    - vcffirstheader < /dev/null
    - vcfsort < /dev/null
    - vcfrandom | grep 'fileformat=VCF'
    - vcfwave -h

about:
  home: https://github.com/vcflib/vcflib
  license: MIT
  summary: Command-line tools for manipulating VCF files
  maintainers:
    - jpuritz
    - AndreaGuarracino

extra:
  identifiers:
    - biotools:vcflib
    - doi:10.1101/023754
