{% set name = "enaBrowserTools" %}
{% set version = "1.7" %}
{% set sha256 = "69948e075652bed49fc10a47b7fbbecfff1bfe324e641105c0dc5142f75a0394" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/enasequence/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - assemblyget_py.patch
    - enadataget.patch  
    - enadataget_py.patch 
    - enagroupget.patch 
    - enagroupget_py.patch 
    - readget_py.patch 
    - sequenceget_py.patch

build:
  number: 0
  noarch: python

requirements:
  run:
    - python
  
test:
  commands:
   - enaDataGet --help |grep enaDataGet >/dev/null
   - enaGroupGet --help |grep enaGroupGet >/dev/null

about:
  home: https://github.com/enasequence/enaBrowserTools
  summary: 'enaBrowserTools is a set of scripts that interface with the ENA web services to download data from ENA easily'
  license: Apache-2.0
