{% set version = "2.0.7" %}
{% set sha256 = "7220a8774e57712e1ed3219d06ffaff210b0e28db6ace67123669075a17bcba8" %}

package:
  name: eukulele
  version: 2.0.7

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps"

source:
  url: https://github.com/AlexanderLabWHOI/EUKulele/archive/refs/tags/v2.0.7.tar.gz
  sha256: {{ sha256 }}

test:
  commands:
    - EUKulele --version | grep '{{ version }}'
    - EUKulele --help

requirements:
  host:
    - python >=3.6
    - pip
    - pytest-runner
  run:
    - python >=3.6
    - numpy ==1.19.5
    - biopython ==1.78
    - pandas ==1.2.0
    - seaborn-base
    - boost-cpp
    - chardet
    - joblib
    - ujson
    - pyyaml
    - matplotlib-base ==3.3.3
    - blast ==2.2.31
    - diamond ==0.9.24

about:
  home: https://github.com/AlexanderLabWHOI/EUKulele
  license: MIT
  license_file: LICENSE
  summary: Easy taxonomic annotation for eukaryotic microbes
