{% set name = "perl-mce" %}
{% set version = "1.889" %}
{% set sha256 = "db6153e474d046fc253050bf53c54002d84cd4ca77d21c2b9df56feeb809bbed" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MA/MARIOROY/MCE-1.889.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-extutils-makemaker
    - perl-file-path
    - perl-getopt-long
    - perl-time-hires
    - perl-socket
    - perl-constant
    - perl-carp
    - perl-storable
    - perl-base
  run:
    - perl
    - perl-file-path
    - perl-getopt-long
    - perl-time-hires
    - perl-socket
    - perl-constant
    - perl-carp
    - perl-storable
    - perl-base

test:
  imports:
    - MCE
    - MCE::Candy
    - MCE::Core::Input::Generator
    - MCE::Core::Input::Handle
    - MCE::Core::Input::Iterator
    - MCE::Core::Input::Request
    - MCE::Core::Input::Sequence
    - MCE::Core::Manager
    - MCE::Core::Validation
    - MCE::Core::Worker
    - MCE::Flow
    - MCE::Grep
    - MCE::Loop
    - MCE::Map
    - MCE::Mutex
    - MCE::Mutex::Channel
    - MCE::Mutex::Flock
    - MCE::Queue
    - MCE::Relay
    - MCE::Signal
    - MCE::Step
    - MCE::Stream
    - MCE::Subs
    - MCE::Util

about:
  home: https://github.com/marioroy/mce-perl
  license: perl_5
  summary: 'Many-Core Engine for Perl providing parallel processing capabilities'
