package:
  name: perl-io-compress
  version: 2.205

source:
  url: https://cpan.metacpan.org/authors/id/P/PM/PMQS/IO-Compress-2.205.tar.gz
  sha256: 657e225cb7bdfbf6decebaf93bc95b0234c279b68fc697a9979c7131a8e44cb9

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-compress-raw-zlib >=2.103
    - perl-compress-raw-bzip2 >=2.103
    - perl-scalar-list-utils
    - perl-extutils-makemaker
  run:
    - perl
    - perl-compress-raw-zlib >=2.103
    - perl-compress-raw-bzip2 >=2.103
    - perl-encode
    - perl-scalar-list-utils

test:
  imports:
    - IO::Compress::Adapter::Bzip2
    - IO::Compress::Adapter::Deflate
    - IO::Compress::Adapter::Identity
    - IO::Compress::Base
    - IO::Compress::Base::Common
    - IO::Compress::Bzip2
    - IO::Compress::Deflate
    - IO::Compress::Gzip
    - IO::Compress::Gzip::Constants
    - IO::Compress::RawDeflate
    - IO::Compress::Zip
    - IO::Compress::Zip::Constants
    - IO::Compress::Zlib::Constants
    - IO::Compress::Zlib::Extra
    - IO::Uncompress::Adapter::Bunzip2
    - IO::Uncompress::Adapter::Identity
    - IO::Uncompress::Adapter::Inflate
    - IO::Uncompress::AnyInflate
    - IO::Uncompress::AnyUncompress
    - IO::Uncompress::Base
    - IO::Uncompress::Bunzip2
    - IO::Uncompress::Gunzip
    - IO::Uncompress::Inflate
    - IO::Uncompress::RawInflate
    - IO::Uncompress::Unzip

about:
  home: http://metacpan.org/pod/IO-Compress
  license: perl_5
  summary: 'IO Interface to compressed data files/buffers'
