{% set version = "3.9.2" %}
{% set sha256 = "18955353e5a19fe13e1732e3424e791e82b707ae7a40e95c5b63ec6095b0ddcd" %}

package:
  name: hmftools-purple
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/purple-v{{ version }}/purple_v{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('hmftools-purple', max_pin="x") }}

requirements:
  run:
    - zlib
    - openjdk >=8
    - xorg-libxtst
    - circos >=0.69.6
    - bioconductor-variantannotation
    - r-cairo
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-tidyr

test:
  commands:
    - 'purple 2>&1 | grep -q "PURPLE"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator
  license: MIT
  license_family: MIT
  summary: Purity/ploidy estimator. Leverages the read depth and tumor BAF to estimate the purity of a sample and generate a copy number profile
