{% set version = "3.9" %}
{% set sha256 = "fe20a1fe1daaa44bd7b7edf1d5a6226af3830eb752b2fbceb503b9df4a8de9fd" %}

package:
  name: hmftools-purple
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/purple-v{{ version }}/purple_v{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - zlib
    - openjdk >=8
    - xorg-libxtst
    - circos >=0.69.6
    - bioconductor-variantannotation
    - r-cairo
    - r-cowplot
    - r-dplyr
    - r-ggplot2
    - r-tidyr

test:
  commands:
    - 'PURPLE -version'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/purity-ploidy-estimator
  license: MIT
  license_family: MIT
  summary: Purity/ploidy estimator. Leverages the read depth and tumor BAF to estimate the purity of a sample and generate a copy number profile
