package:
  name: perl-archive-tar
  version: 3.00

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/Archive-Tar-3.00.tar.gz
  sha256: 0d71196b8c40ef7dae31e372f99e46e49816f8fbd0c8f4fef91ad3f51b99d226

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-pathtools
    - perl-io-compress
    - perl-io-zlib
    - perl-test-harness
    - perl-test-simple
    - perl-module-build
  run:
    - perl
    - perl-pathtools
    - perl-io-compress
    - perl-io-zlib

test:
  # Perl 'use' tests
  imports:
    - Archive::Tar
    - Archive::Tar::Constant
    - Archive::Tar::File


about:
  home: http://metacpan.org/pod/Archive::Tar
  license: perl_5
  summary: 'Manipulates TAR archives'
