{% set version = "1.5" %}
{% set sha256 = "fcecb8a2720fd1614604cc649273fef7aa31bd574e2b6388c310cca763195a00" %}

package:
  name: hmftools-pave
  version: '{{ version }}'

source:
  url: 'https://github.com/hartwigmedical/hmftools/releases/download/pave-v{{ version }}/pave_v{{ version }}.jar'
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - zlib
    - openjdk >=8

test:
  commands:
    - 'pave 2>&1 | grep -q "Pave version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/pave
  license: GPL-3.0-only
  license_family: GPL
  summary: Pave annotates a somatic variant VCF with gene and transcript coding and protein effects.
