{% set version = "13.2.1" %}
{% set sha256 = "064b89c6b7ed27c76c72aefa9d00d07c84c1784816dceaecf168af8c0895a08b" %}

package:
  name: exomiser-cli
  version: {{ version }}

source:
  url: https://github.com/exomiser/Exomiser/releases/download/{{ version }}/exomiser-cli-{{ version }}-distribution.zip
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  run_exports:
    - {{ pin_subpackage('exomiser-cli', max_pin="x") }}

requirements:
  run:
    - openjdk >=8
    - zlib

test:
  commands:
    - exomiser-cli --help

about:
  home: https://github.com/exomiser/Exomiser
  summary: Exomiser prioritiser CLI
  license: AGPL3
  license_file: LICENSE.txt
