{% set name = "perl-dbd-pg" %}
{% set version = "3.17.0" %}
{% set sha256 = "8d900d4c0e749f37218752a6661fb0d3557ab1fccc8dea384cb587c382de219b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/T/TU/TURNSTEP/DBD-Pg-3.17.0.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    weak:
      - {{ name }} ={{ version }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - perl
    - perl-dbi
    - perl-file-temp
    - postgresql
  run:
    - perl
    - perl-dbi
    - postgresql

test:
  imports:
    - DBD::Pg

about:
  home: http://search.cpan.org/dist/DBD-Pg/
  license: perl_5
  summary: 'DBI PostgreSQL interface'
