{% set version = "8" %}
{% set sha256 = "df1d32c6c79aadd57eba6aa8462db4f3bb5c214865fbd4984ee9afe9978867fc" %}

package:
  name: anvio-minimal
  version: {{ version }}

source:
  url: "https://github.com/merenlab/anvio/releases/download/v{{ version }}/anvio-{{ version }}.tar.gz"
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy
    - bottle
    - pysam
    - ete3
    - scipy
    - scikit-learn <0.21
    - django
    - requests
    - psutil ==5.4.3
    - mistune
    - six
    - pandas ==0.25.1
    - matplotlib-base
    - statsmodels
    - colored
    - illumina-utils
    - tabulate
    - numba
    - sqlite >=3.31.1
    - paste
    # these three are critical versions. any changes must be
    # tested with extra attention:
    - pyani ==0.2.10
    - snakemake-minimal ==5.10.0
test:
  commands:
    - anvi-pan-genome --help
    - anvi-script-reformat-fasta --help

about:
  home: http://merenlab.org/software/anvio/
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE.txt
  summary: "An interactive analysis and visualization platform for omics data"
  dev_url:  https://github.com/merenlab/anvio
  
extra:
  container:
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: True
