{% set name = "perl-www-mechanize" %}
{% set version = "2.11" %}
{% set sha256 = "3867e62448a2587ce1ddc4522b3ae925811f69386d6bfb5cc7beecfe49042a1b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SI/SIMBABQUE/WWW-Mechanize-2.11.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-http-server-simple
    - perl-module-build
    - perl-html-form
    - perl-cgi
    - perl-extutils-makemaker
    - perl-test-deep
    - perl-test-fatal
    - perl-test-output
    - perl-test-warnings
    - perl-test-memory-cycle >=1.06
    - perl-encode-locale
    - perl-html-tree
    - perl-libwww-perl
    - perl-http-daemon >=6.12
    - perl-path-tiny
    - perl-test-exception
    - perl-test-nowarnings >=1.04
    - perl-test-taint >=1.08
    - perl-test-warn
  run:
    - perl
    - perl-http-server-simple
    - perl-html-form
    - perl-cgi
    - perl-encode-locale
    - perl-module-build
    - perl-html-tree
    - perl-libwww-perl >=6.45

test:
  imports:
    - WWW::Mechanize
    
about:
  home: https://metacpan.org/pod/WWW::Mechanize
  license: perl_5
  summary: Handy web browsing in a Perl object
