{% set name = "metaprokka" %}
{% set version = "14.7_1" %}
{% set sha256 = "608932a1a9062ea3a5ce824ff30c515fd82f21e9fa33a7025d0fe5d94c938ddc" %}

package:
  name: '{{ name }}'
  version: '{{ version }}'

source:
  url: https://github.com/telatin/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  number: 3
  noarch: generic
  run_exports:
    - {{ pin_subpackage(name, max_pin="x") }}
    
requirements:
  host:
    - perl
    - prokka =1.14.6
    - perl-bioperl >=1.7.2
  run:
    - perl
    - prokka =1.14.6
    - prodigal-gv >=2.11.0
    - perl-fastx-reader >=1.11.0

test:
  commands:
    - metaprokka --listdb
    - metaprokka --version 2>&1 | grep {{ version }}


about:
  home: https://github.com/telatin/{{ name }}
  license: GPL-3.0-only
  license_family: GPL
  license_file: 'LICENSE'
  summary: A specialized version of Prokka using Prodigal-GV for phage annotation and metagenome/metavirome tweaks
  dev_url: https://github.com/telatin/{{ name }}

extra:
  identifiers:
    - biotools:{{ name }}
