{% set version = "0.3.4" %}
{% set name = "fibertools-rs" %}
{% set build_number = "0" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  run_exports:
    - {{ pin_subpackage('fibertools-rs', max_pin="x") }}
  number: {{ build_number }}
  detect_binary_files_with_prefix: False
  # skip: True # [osx]
  rpaths:
    - lib/
    - share/{{ name }}-{{ version }}-{{ build_number }}/lib/
  missing_dso_whitelist:
    - share/{{ name }}-{{ version }}-{{ build_number }}/lib/*
    - "$RPATH/libgomp-a34b3233.so.1"
    - "$RPATH/libcudart-d0da41ae.so.11.0"
  #runpath_whitelist:
  #  - share/{{ name }}-{{ version }}-{{ build_number }}/lib/*
  # overlinking_ignore_patterns:
  #   - share/{{ name }}-{{ version }}-{{ build_number }}/lib/*
  

source:
  url: https://github.com/fiberseq/fibertools-rs/archive/v{{ version }}.tar.gz
  sha256: 68ca148b86280f455edabba53c231627458e7fc0de4538fd8e977f6d7770a2de

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - make
    - cmake
    - unzip
    - curl
  host:
  run:


test:
  commands:
    - ft help


about:
  home: https://github.com/fiberseq/fibertools-rs
  license: MIT
  summary: Mitchell Vollger's rust tools for fiberseq data.


extra:
  recipe-maintainers:
    - mrvollger
