package:
    name: salmon
    version: 0.6.0

build:
  number: 4
  # XXX OSX currently failing due to problem with bundled shared libraries

source:
  - url: https://github.com/COMBINE-lab/salmon/releases/download/v0.6.0/SalmonBeta-0.6.0_OSX_10.11.tar.gz # [osx]
    sha256: 29208adceda97e27b8629f4ed13fe930f4f3720eed9ebcd3e02cb758c348b03c # [osx]
  - url: https://github.com/COMBINE-lab/salmon/archive/v0.6.0.tar.gz # [linux]
    sha256: 2a015c0f95b745fbed575d8610aea7e09cb1af55ca2c68e10ab15826fba263b1 # [linux]

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
    - make
  host:
    - tbb-devel
    - zlib
    - bzip2
    - xz
    - wget
    - boost
    - unzip
  run:
    - tbb

test:
    commands:
      - salmon --help

about:
    home: https://github.com/COMBINE-lab/salmon
    license: GPLv3
    summary: Highly-accurate & wicked fast transcript-level quantification from RNA-seq reads using lightweight alignments.
