{% set version = "5.001" %}
package:
  name: perl-sereal
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/Y/YV/YVES/Sereal-{{ version }}.tar.gz
  sha256: b6ec0724aae85d0187e3d949d41f3d1dbf92d5e2f6314fe95dd05daab3d2206a

build:
  number: 0
  noarch: generic

requirements:
  build:
    - make
  host:
    - perl
    - perl-pathtools
    - perl-test-warn
    - perl-sereal-decoder >={{ version }}
    - perl-test-simple
    - perl-scalar-list-utils
    - perl-extutils-makemaker
    - perl-sereal-encoder >={{ version }}
    - perl-test-longstring

  run:
    - perl
    - perl-sereal-decoder >={{ version }}
    - perl-sereal-encoder >={{ version }}

test:
  imports:
    - Sereal

about:
  home: http://metacpan.org/pod/Sereal
  license: perl_5
  summary: 'Fast, compact, powerful binary (de-)serialization'
