{% set name = "PxBLAT" %}
{% set version = "1.1.10" %}
{% set sha256 = "d20b48ac4c761ad26c680cd1a10e7fb22f581212d5221cbfc2bc7f522a6b81d2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/cauliyang/pxblat/archive/v{{ version }}.tar.gz 
  sha256: ac8132e9a33854963f42e027e7f2a5280ac516076b109cd07cacd26745a16c7b

build:
  number: 0
  skip: True  # [py < 39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vvv
  entry_points:
    - pxblat = pxblat.cli.cli:app
  run_exports:
    - {{ pin_subpackage('pxblat', max_pin="x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python >=3.9
    - pip
    - poetry-core >=1.2.0
    - pybind11 >2.9.1
    - setuptools >=46.4
  run:
    - python
    - loguru
    - pybind11 >=2.10.4
    - rich
    - pysimdjson
    - biopython
    - typer
    - deprecated
    - mashumaro
    - urllib3

test:
  imports:
    - {{ name }}
  commands:
    - pxblat -h

about:
  home: 'https://github.com/ylab-hi/pxblat'
  license: OTHER
  license_file: LICENSE
  summary: "PxBLAT: An Efficient and Ergonomics Python Binding Library for BLAT."
  dev_url: 'https://pypi.org/project/pxblat/'
  doc_url: 'https://pxblat.readthedocs.io/en/latest/'

extra:
  recipe-maintainers:
    - yangyangli
  identifiers:
    - doi:10.1101/2023.08.02.551686
