{% set version = "0.9.1" %}

package:
  name: tower-cli
  version: {{ version }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("tower-cli", max_pin="x.x") }}
    
source:
  - url: https://github.com/seqeralabs/tower-cli/releases/download/v{{ version }}/tw-linux-x86_64 # [linux]
    sha256: 3a8051965ed5bcd489888684587a9fc3323960dcba1203e06d6d45cc7bc78ece # [linux]
    fn: tw # [linux]
  - url: https://github.com/seqeralabs/tower-cli/releases/download/v{{ version }}/tw-osx-x86_64 # [osx]
    sha256: 5505667d8c915ec1809f7d8ef17315a494ca9240e924c986bc58da07c08fad77 # [osx] 
    fn: tw # [osx] 
  - url: https://github.com/seqeralabs/tower-cli/releases/download/{{ version }}/tw-windows-x86_64.exe # [win]
    sha256: a41a028e32079c07affb1c3d9df342e98e257009f3d6634e5109f23a26454641 # [win]
    fn: tw # [win]


test:
  commands:
    - tw --help

about:
  home: "https://github.com/seqeralabs/tower-cli"
  license: "MPL-2.0"
  summary: "The Tower CLI an interface to Nextflow Tower via the CLI"
extra:
  skip-lints:
    - should_be_noarch_generic
    - should_not_use_fn
