{% set name = "perl-parallel-iterator" %}
{% set version = "1.001" %}
{% set sha256 = "72a6191a4fb1fee102b0e7ccc161ec574b0e6b00368286b01999c0f660f21d6e" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/Parallel-Iterator-1.001.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  host:
    - perl
    - perl-storable
    - perl-module-build

  run:
    - perl
    - perl-storable

test:
  imports:
    - Parallel::Iterator

about:
  home: http://metacpan.org/pod/Parallel::Iterator
  license: perl_5
  summary: 'Simple parallel execution'
