{% set name = "perl-dbd-mysql" %}
{% set version = "5.002" %}
{% set sha256 = "8dbf87c2b5b8eaf79cd16507cc07597caaf4af49bc521ec51c0ea275e8332e25" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/D/DV/DVEEDEN/DBD-mysql-5.002.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - perl
    - perl-time-hires
    - perl-test-simple
    - perl-dbi
    - perl-test-deep
    - perl-data-dumper
    - perl-extutils-makemaker
    - mysql-connector-c
    - perl-devel-checklib >=1.09
  run:
    - perl
    - perl-dbi
    - mysql-connector-c

test:
  imports:
    - DBD::mysql

about:
  home: http://dbi.perl.org/
  license: perl_5
  summary: 'A MySQL driver for the Perl5 Database Interface (DBI)'

extra:
  identifiers:
    - biotools:dbd
    - doi:10.1093/nar/gkm964
