{% set name = "perl-html-form" %}
{% set version = "6.10" %}
{% set sha256 = "df8393e35e495a0839f06a63fb65d6922842c180d260554137728a9f092df9d3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/S/SI/SIMBABQUE/HTML-Form-6.10.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl
    - perl-cpan-meta-yaml
    - perl-extutils-parsexs
    - perl-data-dumper
    - perl-extutils-cbuilder
    - perl-file-temp
    - perl-text-abbrev
    - perl-text-parsewords
    - perl-cpan-meta
    - perl-version
    - perl-module-metadata
    - perl-extutils-manifest
    - perl-file-path
    - perl-perl-ostype
    - perl-getopt-long
    - perl-html-parser
    - perl-http-message >=6.18
    - perl-uri

  run:
    - perl
    - perl-text-parsewords
    - perl-cpan-meta
    - perl-version
    - perl-extutils-parsexs
    - perl-data-dumper
    - perl-module-metadata
    - perl-extutils-cbuilder
    - perl-extutils-manifest
    - perl-file-path
    - perl-perl-ostype
    - perl-text-abbrev
    - perl-getopt-long
    - perl-html-parser
    - perl-http-message >=6.18
    - perl-uri
    
test:
  # Perl 'use' tests
  imports:
    - HTML::Form

about:
  home: https://metacpan.org/pod/HTML::Form
  license: perl_5
  summary: Class that represents an HTML form element
