{% set version = "1.24" %}
{% set sha256 = "a6ae81866c8ee3184db3d10a8140e0151c4b89cdb0f204316f531d0a5e817f3d" %}

package:
  name: hmftools-linx
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/linx-v{{ version }}/linx_v{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0

requirements:
  run:
    - openjdk >=8
    - xorg-libxtst
    - r-tidyr
    - r-dplyr
    - r-ggplot2
    - r-cowplot
    - r-magick
    - bioconductor-gviz
    - circos >=0.69.6

test:
  commands:
    - 'linx 2>&1 | grep -q "LINX version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/linx
  license: GPL-3.0-only
  license_family: GPL
  summary: Linx is an annotation, interpretation and visualisation tool for structural variants
