{% set version = "1.24.1" %}
{% set sha256 = "a17054866ea783a7d2d9cb071ddd750d98bc513783cac590af63f1c0367441e8" %}

package:
  name: hmftools-linx
  version: '{{ version }}'

source:
  url: https://github.com/hartwigmedical/hmftools/releases/download/linx-v{{ version }}/linx_v{{ version }}.jar
  sha256: '{{ sha256 }}'

build:
  noarch: generic
  number: 0
  run_exports:
    - {{ pin_subpackage('hmftools-linx', max_pin="x") }}

requirements:
  run:
    - openjdk >=8
    - xorg-libxtst
    - r-tidyr
    - r-dplyr
    - r-ggplot2
    - r-cowplot
    - r-magick
    - bioconductor-gviz
    - circos >=0.69.6

test:
  commands:
    - 'linx 2>&1 | grep -q "LINX version"'

about:
  home: https://github.com/hartwigmedical/hmftools/tree/master/linx
  license: GPL-3.0-only
  license_family: GPL
  summary: Linx is an annotation, interpretation and visualisation tool for structural variants
