{% set package = "ucsc-big-tools" %}
{% set version = "455" %}
{% set sha256 = "60f18fc4ea8b3702272b37c6579722746b6e015fea686f66030e52549da38cd2" %}

package:
  name: {{ package }}
  version: {{ version }}

source:
  url: "http://hgdownload.cse.ucsc.edu/admin/exe/userApps.archive/userApps.v{{ version }}.src.tgz"
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [osx]
  binary_relocation: False
  run_exports:
    - {{ pin_subpackage("ucsc-big-tools", max_pin="x") }}
  #ignore_run_exports:
    #- libpng
    #- libuuid

requirements:
  build:
    - rsync
    #- make
    #- {{ compiler('c') }}
    #- {{ compiler('cxx') }}
    #- binutils # [linux]
  host:
    #- libpng
    #- libuuid
    #- mysql-connector-c
    #- openssl
    #- libopenssl-static
    #- zlib
  run:
    #- libpng
    #- libuuid
    #- mysql-connector-c
    #- openssl

test:
  commands:
    - which bigBedInfo
    - which bigBedNamedItems
    - which bigBedSummary
    - which bigBedToBed
    - which bigChainBreaks
    - which bigGenePredToGenePred
    - which bigHeat
    - which bigGuessDb
    - which bigMafToMaf
    - which bigPslToPsl
    - which bigWigAverageOverBed
    - which bigWigCluster
    - which bigWigCat
    - which bigWigMerge
    - which bigWigCorrelate
    - which bigWigSummary
    - which bigWigInfo
    - which bigWigToBedGraph
    - which bigWigToWig

about:
  home: "http://hgdownload.cse.ucsc.edu/admin/exe/"
  license: "varies; see http://genome.ucsc.edu/license"
  description: 'A package containing any UCSC kent tools matching the following globs: big*,'
  summary: "All of the ucsc kent tools"

extra:
  skip-lints:
    # repackaged binary
    - should_be_noarch_generic
