name: Bulk branch
on:
  push:
    branches:
      - bulk
      - bulk-osx-debug
jobs:

  build-osx:
    name: Bulk OSX Builds
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        runner: [0]
    steps:
    - uses: actions/checkout@v1

    - name: Fetch common.sh
      run: |
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/common.sh

    - name: Restore cache
      id: cache
      uses: actions/cache@v1
      with:
        path: /Users/runner/bioconda
        key: ${{ runner.os }}--bulk--${{ hashFiles('**/common.sh') }}

    - name: Setup Bioconda-utils
      if: steps.cache.outputs.cache-hit != 'true'
      run: |

        # remove existing installation on macOS runners
        sudo rm -rf /usr/local/miniconda

        export TERM=xterm-color
        export FORCE_COLOR=1

        set -x

        # Extract the versions we should be using from the previously-downloaded common.sh
        BIOCONDA_UTILS_TAG=$(grep "^BIOCONDA_UTILS_TAG=" common.sh | cut -f2 -d "=" | sed "s/^v//g")
        MINICONDA_VER=$(grep "^MINICONDA_VER=" common.sh | cut -f2 -d "=")

        # Basic miniconda installation with bioconda channels configured

        curl "https://repo.anaconda.com/miniconda/Miniconda3-${MINICONDA_VER}-MacOSX-x86_64.sh" > miniconda.sh
        head miniconda.sh
        bash miniconda.sh -b -p "${HOME}/miniconda"
        export PATH="${HOME}/miniconda/bin:${PATH}"
        echo $PATH
        ls -lrth ${HOME}/miniconda
        which conda
        conda config --set always_yes yes
        conda config --system --add channels defaults
        conda config --system --add channels bioconda
        conda config --system --add channels conda-forge
        conda config --system --set channel_priority strict
        conda info

        conda install -y conda-build # toml mamba

        # Set local channel as highest priority
        mkdir -p "${HOME}/miniconda/conda-bld/{noarch,linux-64,osx-64}"
        conda index "${HOME}/miniconda/conda-bld"
        conda config --system --add channels "file://${HOME}/miniconda/conda-bld"

        conda build .github/workflows/bioconda-utils

        conda install bioconda-utils=1.0.999

        set -x
        ${HOME}/miniconda/bin/run_conda_forge_build_setup
        set +x


    - name: Build and upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
        QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
        # Mimic circleci
        OSTYPE: "darwin"
        CI: "true"
      run: |
        eval "$(${HOME}/miniconda/bin/conda shell.bash hook)"
        conda activate base
        echo '============'
        conda info --all
        conda config --show-sources
        python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
        echo '============'
        bioconda-utils build recipes config.yml \
          --worker-offset ${{ matrix.runner }} --n-workers 1
        conda clean -y --all
