name: Bulk branch
on:
  push:
    branches:
      - bulk
      - bulk-osx-debug
jobs:

  build-osx:
    name: Bulk OSX Builds
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        runner: [0]
    steps:
    - uses: actions/checkout@v1

    - name: Fetch common.sh
      run: |
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/common.sh

    - name: Restore cache
      id: cache
      uses: actions/cache@v1
      with:
        path: /Users/runner/bioconda
        key: ${{ runner.os }}--bulk--${{ hashFiles('**/common.sh') }}

    - name: Setup Bioconda-utils
      if: steps.cache.outputs.cache-hit != 'true'
      uses: bioconda/bioconda-actions/bioconda_recipes_setup/@bulk
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

    - name: OSX stuff
      run: |

    - name: Build and upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
        QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
        # Mimic circleci
        OSTYPE: "darwin"
        CI: "true"
      run: |
        . /Users/runner/bioconda/etc/profile.d/conda.sh
        conda activate base
        echo '============'
        conda info --all
        conda config --show-sources
        python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
        echo '============'
        bioconda-utils build recipes config.yml \
          --worker-offset ${{ matrix.runner }} --n-workers 1
        conda clean -y --all
