name: Bulk branch
on:
  push:
    branches:
      - bulk
      - bulk-osx-debug
jobs:

  build-osx:
    name: Bulk OSX Builds
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        runner: [0]
    steps:
    - uses: actions/checkout@v1

    - name: Fetch common.sh
      run: |
        wget https://raw.githubusercontent.com/bioconda/bioconda-common/bulk/common.sh

    - name: Restore cache
      id: cache
      uses: actions/cache@v1
      with:
        path: /Users/runner/bioconda
        key: ${{ runner.os }}--bulk--${{ hashFiles('**/common.sh') }}

    - name: Setup Bioconda-utils
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        #
        # The following lines are from reverse-engineering the
        # conda-forge-ci-setup repo,
        # https://github.com/conda-forge/conda-forge-ci-setup-feedstock.
        # Relevant links in that repo are provided for each chunk.
        #
        # https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/df29a72bf13e7083d5e1c4126f94fe756151ffdb/.ci_support/osx_64_python3.10.____cpython.yaml#L2
        MACOSX_SDK_VERSION=10.9
        MACOSX_DEPLOYMENT_TARGET=10.9

        # https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/404bf0a7c73205c1cdf7900565f0f7b1ee4a5062/recipe/run_conda_forge_build_setup_osx#L32
         OSX_SDK_DIR="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"

        # https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/df29a72bf13e7083d5e1c4126f94fe756151ffdb/recipe/download_osx_sdk.sh#L25-L27
        export CONDA_BUILD_SYSROOT="${OSX_SDK_DIR}/MacOSX${MACOSX_SDK_VERSION}.sdk"
        curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX${MACOSX_SDK_VERSION}.sdk.tar.xz
        mkdir -p "$(dirname "$CONDA_BUILD_SYSROOT")"
        tar -xf MacOSX${MACOSX_SDK_VERSION}.sdk.tar.xz -C "$(dirname "$CONDA_BUILD_SYSROOT")"

        # https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/404bf0a7c73205c1cdf7900565f0f7b1ee4a5062/recipe/run_conda_forge_build_setup_osx#L42-L43
        plutil -replace MinimumSDKVersion -string ${MACOSX_SDK_VERSION} $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist
        plutil -replace DTSDKName -string macosx${MACOSX_SDK_VERSION}internal $(xcode-select -p)/Platforms/MacOSX.platform/Info.plist


        # Extract the versions we should be using from the previously-downloaded common.sh
        BIOCONDA_UTILS_TAG=$(grep "^BIOCONDA_UTILS_TAG=" common.sh | cut -f2 -d "=" | sed "s/^v//g")
        MINICONDA_VER=$(grep "^MINICONDA_VER=" common.sh | cut -f2 -d "=")

        # Basic miniconda installation with bioconda channels configured
        curl "https://repo.continuum.io/miniconda/Miniconda3-${MINICONDA_VER}-MacOSX-x86_64.sh" > miniconda.sh
        bash miniconda.sh -b -p "${HOME}/miniconda"
        export PATH="${HOME}/miniconda/bin:${PATH}"
        conda config --set always_yes yes
        conda config --system --add channels defaults
        conda config --system --add channels bioconda
        conda config --system --add channels conda-forge
        conda info
        conda install -y "bioconda-utils=${BIOCONDA_UTILS_TAG}" __osx==10.9
        conda clean -y --all

        # Set local channel as highest priority
        mkdir -p "${HOME}/miniconda/conda-bld/{noarch,linux-64,osx-64}"
        conda index "${HOME}/miniconda/conda-bld"
        conda config --system --add channels "file://${HOME}/miniconda/conda-bld"


    - name: Build and upload
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        INVOLUCRO_AUTH: ${{ secrets.INVOLUCRO_AUTH }}
        QUAY_OAUTH_TOKEN: ${{ secrets.QUAY_OAUTH_TOKEN }}
        # Mimic circleci
        OSTYPE: "darwin"
        CI: "true"
      run: |
        eval "$(conda shell.bash hook)"
        conda activate base
        echo '============'
        conda info --all
        conda config --show-sources
        python -c 'import bioconda_utils.utils as u ; import pathlib as p ; print(*(f"{f}:\n{p.Path(f).read_text()}" for f in u.load_conda_build_config().exclusive_config_files), sep="\n")'
        echo '============'
        bioconda-utils build recipes config.yml \
          --worker-offset ${{ matrix.runner }} --n-workers 1
        conda clean -y --all
